social/blog/urls.py
from django.urls import path
from .import views
from django.conf.urls import url
from blog.feeds import LatestPostsFeed
app_name = 'blog'

urlpatterns = [
# post views
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('contact/',views.contact, name='contact'),
    path('<int:pk>/view/', views.post_detail, name='post_detail'),
    path('<int:pk>/share/', views.share, name='share'),
    path('create/', views.create_post, name ='create_post'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    url(r'^category$', views.show_category, name='category'),
    path('post_random/',views.post_random, name='posts'),
    path('newsletter/', views.news, name= 'new'),
    path('confirm/', views.confirm, name='confirm'),
    path('delete/', views.delete, name='delete'),
]

social/social/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/',include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
    path('blog/', include('blog.urls', namespace='blog')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

social/blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone
from taggit.managers import TaggableManager
from django.conf import settings
from mptt.models import MPTTModel, TreeForeignKey
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

class PublishedManager(models.Manager):
        def get_queryset(self):
                return
                super(PublishedManager,self).get_queryset()\
                        .filter(status='Draft')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),)
    title = models.CharField(max_length=250)
    category = models.ForeignKey('Category', null=True, blank=True, on_delete = models.CASCADE)
    slug = models.SlugField(max_length=250,
             unique_for_date='publish')
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='images/%Y/%m/%d/')
    active = models.BooleanField(default=False)
    status = models.CharField(max_length=10,
            choices=STATUS_CHOICES,
            default='publish')
    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager  
    class Meta: 
                ordering = ('-publish',)
                def __str__(self):
                    return self.title
    def approve_post(self):
        
        return self.published.filter(active=False)
    def approve_comments(self):
        return self.comments.filter(active=False)
    def get_absolute_url(self):
            return reverse('blog:post_detail',kwargs={'pk':self.pk})
    tags = TaggableManager()
    def get_cat_list(self):
        k = self.category # for now ignore this instance method
        breadcrumb = ["dummy"]
        while k is not None:
            breadcrumb.append(k.slug)
            k = k.parent
        for i in range(len(breadcrumb)-1):
            breadcrumb[i] = '/'.join(breadcrumb[-1:i-1:-1])
        return breadcrumb[-1:0:-1]
class Comment(models.Model):
        post = models.ForeignKey(Post,
            on_delete=models.CASCADE,
            related_name='comments')
        name = models.CharField(max_length = 25)
        email = models.EmailField()
        body = models.TextField()
        created = models.DateTimeField(auto_now_add=True)
        updated = models.DateTimeField(auto_now=True)
        active = models.BooleanField(default=False)
        class meta:
                ordering = ('created',)
        def __str__(self):

                return f'Comment by {self.name} on {self.post}'
class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField()
    parent = models.ForeignKey('self',blank=True, null=True ,related_name='children', on_delete = models.CASCADE)

    class Meta:
        #enforcing that there can not be two categories under a parent with same slug
        
        # __str__ method elaborated later in post.  use __unicode__ in place of
        
        # __str__ if you are using python 2

        unique_together = ('slug', 'parent',)    
        verbose_name_plural = "categories"     

    def __str__(self):                           
        full_path = [self.name]                  
        k = self.parent
        while k is not None:
            full_path.append(k.name)
            k = k.parent
        return ' -> '.join(full_path[::-1])

class Subscriber(models.Model):
    email = models.EmailField(unique=True)
    conf_num = models.CharField(max_length=15)
    confirmed = models.BooleanField(default=False)
    
    def __str__(self):
        return self.email + "(" + ("not " if not self.confirmed else "") + "confirmed)"
class Newsletter(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    subject = models.CharField(max_length=150)
    contents = models.FileField(upload_to='uploaded_newsletters/')

    def __str__(self):
        return self.subject + " " + self.created_at.strftime("%B %d, %Y")

    def send(self, request):
        contents = self.contents.read().decode('utf-8')
        subscribers = Subscriber.objects.filter(confirmed=True)
        sg = SendGridAPIClient(settings.SENDGRID_API_KEY)
        for sub in subscribers:
            message = Mail(
                    from_email=settings.FROM_EMAIL,
                    to_emails=sub.email,
                    subject=self.subject,
                    html_content=contents + (
                        '<br><a href="{}/delete/?email={}&conf_num={}">Unsubscribe</a>.').format(
                            request.build_absolute_uri('/delete/'),
                            sub.email,
                            sub.conf_num))
            sg.send(message)

social/blog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('author','title','slug','body','image')
        widgets = {
            'title': forms.TextInput(),
            'body': forms.Textarea(),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','email','body')
        widgets = {
            'name': forms.TextInput(),
            'body': forms.Textarea(),
        }
class Emailshare(forms.Form):
    name = forms.CharField(max_length =25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)
class Contact(forms.Form):
    name = forms.CharField(max_length=20)
    email  = forms.EmailField()
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)

class SubscriberForm(forms.Form):
    email = forms.EmailField(label="your email",max_length=100,widget= forms.EmailInput(attrs={'class':'form-control'}))

social/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage,\
PageNotAnInteger
from .models import Post, Comment, Category, Subscriber
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (TemplateView,ListView,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)
from .forms import CommentForm,PostForm, Emailshare,Contact, SubscriberForm
from django.core.mail import send_mail, BadHeaderError
from taggit.models import Tag
from django.db.models import Count
from django.core.mail import send_mail
from django.shortcuts import render
from django.http import HttpResponse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
import random
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

# Create your views here.
def post_list(request, **kwargs):
    object_list = Post.objects.all()
    tag = None
    tag_slug = kwargs.get("tag_slug")
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    print(page)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
    # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
    # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    if tag:
        return render(request, 'blog/post/list.html', {'posts': posts,'tag': tag})
    else:
        return render(request, 'blog/post/list.html', {'posts': posts})
def create_post(request):
    sent = False
    if request.method == 'POST':
        forms = PostForm(data =request.POST, files=request.FILES)
        if forms.is_valid():
            forms.save()
            return redirect('/blog')
            sent = True
    else:
        forms = PostForm()
    return render(request,'blog/post/create.html',{'forms':forms })
def post_detail(request,pk):
        post = get_object_or_404(Post, pk=pk,status='published')
        # List of active comments for this post
        comments = post.comments.filter(active=True)
        new_comment = None
        if request.method == 'POST':
        # A comment was posted
            comment_form = CommentForm(data=request.POST)
            if comment_form.is_valid():
            # Create Comment object but don't save to database yet
                new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER','/') )
        else:
            comment_form = CommentForm()

        post_tags_ids = post.tags.values_list('id', flat=True)
        similar_posts = Post.objects.filter(tags__in=post_tags_ids).exclude(id=post.id)
        similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
        return render(request,'blog/post/detail.html',{'post': post,'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,'similar_posts':similar_posts})

def contact(request):
    sent = False
    if request.method == 'POST':
        contact = Contact(data=request.POST)
        if contact.is_valid():
            name = contact.cleaned_data['name']
            sender = contact.cleaned_data['email']
            subject = contact.cleaned_data['subject']
            message = contact.cleaned_data['message']
            recipients = ['agrictime@gmail.com']
            try:
                send_mail(subject, message, sender, recipients)
            except BadHeaderError:
                return HttpResponse('Invalid header found')
        sent = True
    else: 
        contact = Contact()
    return render(request, 'blog/post/contact.html', {'contact': contact, 'sent':sent})
def share(request, pk):
    post = get_object_or_404(Post, pk=pk,status='published')
    sent = False
    if request.method == 'POST':
        form = Emailshare(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " \
            f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
            f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, '',[cd['to']])
            sent = True
            return redirect('blog:post_detail',pk=pk)
    else:
        form = Emailshare()
    return render(request, 'blog/post/share.html', {'post': post,
        'form': form, 'sent':sent})

def show_category(request,hierarchy= None):
    category_slug = hierarchy.split('/')
    category_queryset = list(Category.objects.all())
    all_slugs = [ x.slug for x in category_queryset ]
    parent = None
    for slug in category_slug:
        if slug in all_slugs:
            parent = get_object_or_404(Category,slug=slug,parent=parent)
        else:
            instance = get_object_or_404(Post, slug=slug)
            breadcrumbs_link = instance.get_cat_list()
            category_name = [' '.join(i.split('/')[-1].split('-')) for i in breadcrumbs_link]
            breadcrumbs = zip(breadcrumbs_link, category_name)
            return render(request, "blog/post/detail.html", {'instance':instance,'breadcrumbs':breadcrumbs})

    return render(request,"blog/post/categories.html",{'post_set':parent.post_set.all(),'sub_categories':parent.children.all()})

def post_random(request):
    poster = Post.objects.order_by("?")[:4]
    return render(request, "blog/post/random_post.html", {'poster':poster})

def random_digits():
    return "%0.12d" % random.randint(0, 999999999999)

@csrf_exempt
def news(request):
    if request.method == 'POST':
        sub = Subscriber(email=request.POST['email'], conf_num=random_digits())
        sub.save()
        message = Mail(
            from_email=settings.FROM_EMAIL,
            to_emails=sub.email,
            subject='Newsletter Confirmation',
            html_content='Thank you for signing up for my email newsletter! \
                Please complete the process by \
                <a href="{}/confirm/?email={}&conf_num={}"> clicking here to \
                confirm your registration</a>.'.format(request.build_absolute_uri('/confirm/'),
                                                    sub.email,
                                                    sub.conf_num))
        sg = SendGridAPIClient(settings.SENDGRID_API_KEY)
        response = sg.send(message)
        return render(request, 'blog/base.html', {'email': sub.email, 'action': 'added', 'form': SubscriberForm()})
    else:
        return render(request, 'blog/base.html', {'form': SubscriberForm()})
def confirm(request):
    sub = Subscriber.objects.get(email=request.GET['email'])
    if sub.conf_num == request.GET['conf_num']:
        sub.confirmed = True
        sub.save()
        return render(request, 'blog/base.html', {'email': sub.email, 'action': 'confirmed'})
    else:
        return render(request, 'blog/base.html', {'email': sub.email, 'action': 'denied'})
def delete(request):
    sub = Subscriber.objects.get(email=request.GET['email'])
    if sub.conf_num == request.GET['conf_num']:
        sub.delete()
        return render(request, 'blog/base.html', {'email': sub.email, 'action': 'unsubscribed'})
    else:
        return render(request, 'blog/base.html', {'email': sub.email, 'action': 'denied'})

social/blog/templates/blog/post/categories.html
{% extends 'base.html' %}
{% load static  %}
{% block content %}
<br>
{% if sub_categories %}
    <h3>Sub Categories</h3>
    {% for i in sub_categories %}s 
        <a href="{{ i.slug }}"> {{ i.name }} </a>
    {% endfor %}
{% endif %}

<div class="row small-up-1 medium-up-3" >
{% if post_set %}
{% for i in post_set %}
    <div class="columns">
        <div class=" card-article-hover card">
          <a href="{{ i.slug }}">
            <img  src="{{ i.cover_photo.url }}">
          </a>
          <div class="card-section">
            <a href="{{ i.slug }}">
              <h6 class="article-title">{{ i.title | truncatechars:30}}</h6>
            </a>
          </div>
          <div class="card-divider flex-container align-middle">
            <a href="" class="author">{{ i.user.get_full_name }}</a>
          </div>
          <div class="hover-border">
          </div>
        </div>
    </div>
{% endfor %}
{% endif %}
</div>
{% endblock %}

 

social/blog/templates/blog/post/contact.html
{% extends "blog/base.html" %}
{% block title %}contact us{% endblock %}
{% block content %}
{% if sent %}
    <h1>We will be with you shortly</h1>
    {% else %}
        <h1>Contact us</h1>
        <form method="post">
            <input type = "hidden" id ="previous_page" value = "/previous/page/url">
            {{ contact.as_p }}
            {% csrf_token %}
            <button class= "btn btn-primary" type= "submit" id="submit">Submit</button>
        </form>
        <script>
            prev = document.getElementById("previous_page");
            prev.value = document.referrer
        </script>
{% endif %}
{% endblock %}

social/blog/templates/blog/post/create.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form" enctype="multipart/form-data">
    {% csrf_token %}
    {{forms.as_p}}
    <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

social/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load thumbnail %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
<ul class="breadcrumbs">
    <li><a href="/">Home</a></li>
        {% for slug,name in breadcrumbs %}
            <li><a href="/category/{{ slug }}">{{ name }}</a></li>
        {% endfor %}
  </ul>
  
   
<h1>{{ post.title }}</h1>
<p class="date">
Published {{ post.publish }} by {{ post.author }}
</p>
<img src="{% thumbnail post.image 180x180 %}">
{{ post.body|markdown }}
<p>
    <a href="{% url "blog:share" post.id %}">
    Share this post
    </a>
    </p>
{% with comments.count as total_comments %}
    <h2>
    {{ total_comments }} comment {{ total_comments|pluralize }}
    </h2>
    
{% endwith %}

<p class="tags">
    Tags:
        {% for tag in post.tags.all %}
        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
        {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
        {% endfor %}
</p>
<h2>Similar posts</h2>
{% for post in similar_posts %}
<p>
<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</p>
{% empty %}
There are no similar posts yet.
{% endfor %}
{% for comment in comments %}
    <div class="comment">
        <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
        </p>
        {{ comment.body|linebreaks }}
    </div>
    {% empty %}
    <p>There are no comments yet.</p>
{% endfor %}

{% if new_comment %}
    <h2>Your comment has been added.</h2>
{% else %}
<h2>Add a new comment</h2>
<form method="post">
    {{ comment_form.as_p }}
{% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
</form>
{% endif %}

{% endblock %}

social/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

social/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load thumbnail %}
{% load blog_tags %}
{% block title %}My Blog{% endblock %}
{% block content %}
<h1>My Blog</h1>


{% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
{% endif %}

{% for post in posts %}
    <h2>
    <a href="{{ post.get_absolute_url }}">
            {{ post.title }}
    </a>
    </h2>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {% thumbnail post.image "100x80" crop="80%" as im %}
<a href="{{ post.get_absolute_url }}">
<img src="{{ im.url }}" class="item-img">
</a>
<div>{{ post.body|markdown|truncatewords_html:30 }}</div>
{% endfor %}
{% include "pagination.html" with page=posts %}
{% endblock %}

social/blog/templates/blog/post/random_post.html
{% extends "blog/base.html" %}
<h2>my random post</h2>
<p>
    <a href="{{ poster.get_absolute_url }}">{{ poster.title }}</a>
</p>

social/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
{% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
    "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
{% endif %}
{% endblock %}